# Generated by Django 2.2 on 2019-12-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20191225_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='nonce_str',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='微信随机加密串'),
        ),
    ]
